import DeviceInfo from 'react-native-device-info';

const BaseText = {
    // GoogleLocationAuthKey: '',
    WelcomeMasstor: 'Welcome to Masstor',
    LogSign: 'Log In / Sign Up',
    Explore: 'Explore',
    Orcontinuewith: 'Or continue with',
    EnterYourMobileNumber: 'Enter Your Mobile Number',
    Submit: 'Submit',
    ResendCode: 'Resend code in',
    Weaccesslocation: 'We access your location',
    Deny: 'Deny',
    Allow: 'Allow',
    EnterYourLocation: 'Enter Your Location',
    EditProfile: 'Edit Profile',
    FirstName: 'First Name',
    LastName: 'Last Name',
    MobileNumber: 'Mobile Number',
    EmailId: 'Email Id',
    SaveChanges: 'Save Changes',
    MySchool: 'My School',
    emptySelectedSchoolTitle: 'No school selected for enquiry yet, Explore Schools for enquiry.',
    ExploreSchools: 'Explore Schools',
    CheckStatus: 'Check Status',
    cameraAccessNote: "We access your camera",
    cameraAccessBtnText: "Allow",
    etSubjects: "Subjects",
    etTime: "Time - 60 Minutes",
    etTime1: " for each subject",
    etQues: "Total Questions - 15",
    etQues1: " in each subject",
    etMarks: "Total Marks - 30",
    etMarks1: " in each subject",
    etBtnText: "Proceed to Test",
    tEng: "English",
    tMath: "Math",
    tSci: "Science",
    tBtnNext: "Next",
    tBtnBack: "Back",
    tCompMsg1: "Wooh! You have completed ",
    tCompMsg2: " test,\nNow move on next subjects.",
    tBtnSubmit: "Submit",
    tCompBtnNext: "Next Subject",
    CompareSchool: 'Compare School',
    ComapreSchoolTitle: 'Confused between too many? Compare them on multiple criteria such as fees, facility, admi -ssion & more.',
    Compare: 'Compare',
    Weareready: 'We are ready.',
    SelectSchools: 'Select Schools to get started.',
    Favourite: 'Favourite',
    EmptyFaviourtSchoolTitle: 'Click on heart and add your favourite Schools.',
    ApplyNow: 'Apply Now',
    testCompleteNextBtn: "My School",
    etHeaderTitle: "Entrance Test",
    testCompMsg: "Wooh! You have completed all subject Test.",
    examComp1: 'Dear',
    examComp2: 'Your Entrance Test has been submitted to ',
    examComp3: 'Please wait for the Entrance Test Result. All the best for result.',
    examComp4: 'Thanks',
    localitiesTitle: "Discover Localities",
    failTestTitle: "Entrance Test Result",
    failTestNote: "Entrance Test Result Fail",
    failTestBtnText: "Try Another School",
    pendTestNote: "Entrance Test Result Pending",
    successTestNote: "Entrance Test Result Passed",
    successTestBtnText: "Proceed to Addmission",
    testFailTitle: "Oh No",
    testFailNote: "We’re sorry, You are not passed in Entrance Test.",
    testFailBtnText: "Check your Marks",
    testPendTitle: "Wait, Wait, Wait",
    testPendNote: "Good thing takes time, All the best for Result.",
    testPendBtnText: "Update Soon",
    testSuccessTitle: "Congratulations",
    testSuccessNote: "Amazing, You are passed in Entrance Test.",
    testSuccessBtnText: "Check your Marks",
    failStatusText: "Fail",
    passStatusText: "Passed",
    pendStatusText: "Result Pending",
    LocalitywiseSchool: 'Locality wise School',
    Chooseyourstandard: 'Choose your standard',
    Continue: 'Continue',
    SectionOverview: "Overview",
    SectionFeeStruct: "Fee Structure",
    SectionCriteria: "Criteria",
    SectionAdmision: "Admission",
    SectionFAQ: "FAQs",
    SectionReview: "Reviews",
    modOfLearn: "Mode of Learning",
    onlineText: "Online",
    offlineText: "Offline",
    admissTimeline: 'Admission Timeline',
    aboutSchool: 'About School',
    schoolAmenities: "School Amenities",
    staff: "Staff",
    overviewApplyBtnText: "Apply for Admission",
    overviewApplyBtnText1: "Online Classes - 1500",
    overviewFeeBtntext: "Get Fee Structure",
    overviewFeeBtntext1: "Free",
    AdvanceSearch: 'Advance Search?',
    Standard: 'Standard',
    Board: 'Board',
    LearningMode: 'Learning Mode',
    SchoolType: 'School Type',
    SchoolFormat: 'School Format',
    COEDStatus: 'CO-ED Status',
    Languageofintruction: 'Language of intruction',
    Applyforaddmission: 'Apply for addmission',
    ContinueKYCProcess: 'Continue for KYC Process',
    Completeyourapplicationform: 'Complete your application',
    MobileOrEmail: 'Mobile Number or Email address',
    OTPVerification: 'OTP Verification',
    Qualification: 'Qualification',
    IAm: 'I Am',
    ParentsPhoneNumber: 'Parents/Guardian Phone Number',
    Occupation: 'Occupation',
    State: 'State',
    City: 'City',
    TermConditionapplied: 'Term & Condition applid*',
    admissionCriteria: 'Admission Criteria',
    documentsCriteria: 'Documents',
    AgeCriteria: 'Age Criteria',
    admissionProcess: 'Admission Process',
    SubmitApproval: 'Submit & Wait for Approval',
    CompleteKYCProcess: 'Complete KYC Process',
    SubmityourbelowDocuments: 'Submit your below Documents',
    feeStructure: "Fee Structure",
    faqTitle: 'Question in your mind',
    reviewTitle: 'People talk about School',
    reviewHeading1: 'Rate this School!',
    reviewPH: 'Write your comment...……….',
    reviewSubmitBtnText: 'Submit',
    howtoApplyAdmis: "How to apply for admission",
    htaapOnlineProcedure: "Online Admission Procedure",
    htaapOfflineProcedure: "Offline Admission Procedure",
    htaapLearningMode: "Select Mode Of Learning",
    htaapBtnText: "Apply for addmission",
    noInternetTitle: "Page Not Found",
    noInternetMsg: "Check your internet connection, then refresh the page.",
    noInternetBtnText: "Refresh",
    hiwTitle: 'How masstor works',
    hiwText: 'How it works',
    hiwBtnText: 'Watch Video',
    simpProText: 'Our Simplified Process',
    SeeMore: 'See More',
    CustomizeSearch: 'Customize Search',
    SchoolsNearYou: 'Schools Near You',
    TrendingSchools: 'Trending Schools',
    spExpl: 'Explore & Search',
    spCompSch: 'Compare Schools',
    spAdminTra: 'Admission Tracker',
    spResuTra: 'Result Tracker',
    spSingleKYC: 'Single KYC Form',
    schoolForYouHeaderTitle: 'School For You',
    admissioniFormInfo: 'By filling up this Single KYC Form, you can apply in multiple schools at just a single click.',
    AdmissionOpen: 'Admission Open',
    CheckAdmissionDate: 'Check Admission Date',
    popupOtpSndngTitle: 'Sending OTP',
    popupOtpSndngMsg: 'We are sending 4 digit OTP to',
    popupOtpSndngBtnText: 'Change',
    popupOtpSentTitle: 'OTP Sent',
    popupOtpSentMsg: 'We have successfully sent an OTP to',
    popupOtpSentBtnText: 'Change',
    popupOtpDetectTitle: 'Detecting OTP',
    popupOtpDetectMsg: 'We have successfully sent an OTP to',
    popupOtpDetectBtn1Text: 'Change',
    popupOtpDetectBtn2Text: 'Enter Manually',
    popupOtpFailTitle: 'Oops!',
    popupOtpFailMsg: 'Looks like we failed to detect OTP Automatically.',
    popupOtpFailBtn2Text: 'Resend',
    popupOtpFailBtn1Text: 'Enter Manually',
    popupOtpSuccessTitle: 'OTP Verification Successful',
    popupLogoutTitle: "Come back Soon!",
    popupLogoutMsg: 'Are you sure you want to Log out?',
    popupLogoutBtn1Text: 'Yes',
    popupLogoutBtn2Text: 'No',
    popupAccessReqTitle: 'Sending Access Request',
    popupAccessReqMsg: 'Your request for free access is being submitted',
    popupAccessSubTitle: 'Request Submitted',
    popupAccessSubMsg: 'You will be notified for the access shortly.',
    popupFeeStrctTitle: 'Get Fees Structure',
    popupFeeStrctMsg: 'We will send your Fee Structure on this number.',
    popupFeeStrctMsg1: 'We will send your Fee Structure on this email.',
    popupFeeStrctMPH: 'Enter Mobile Number',
    popupFeeStrctEPH: 'Enter email address',
    popupFeeStrctBtnTextSend: 'Send',
    popupFeeStrctTOC: 'Terms & Conditions',
    popupFeeStrctPP: 'Privacy Policy',
    popupFeeStrctSentTitle: 'Fee Structure Sent',
    popupFeeStrctSentMsg: 'Your Fees Structure has been successfully send to',
    popupFeeStrctBtnText: 'Change',
    popupKYCTitle: 'Single KYC Form',
    popupKYCMsg: 'Your KYC has been successfully Submitted',
    popupKYCBtn1Text: 'Track Status',
    popupKYCBtn2Text: 'Explore More',
    popupPaySuccTitle: 'Congratulations',
    popupPaySuccMsg: 'Your payment is successfully done.',
    popupPaySuccBtnText: 'Download Payment Recipt',
    popupPayFailTitle: 'Oh No',
    popupPayFailMsg: 'We’re sorry about something went wrong.',
    popupPayFailBtnText: 'Try Again',
    popupAdmiSucTitle: 'Congratulations',
    popupAdmiSucMsg: 'Your Admission fee has been successfully paid.',
    popupAdmiDoneTitle: 'Welcome to your campus',
    popupAdmiDoneBtnText: 'Okay',
    popupDeleteAccTitle: 'Delete Account',
    popupDeleteAccMsg: 'Are you sure you want to delete your account.',
    popupDeleteAccBtn1Text: 'Yes',
    popupDeleteAccBtn2Text: 'No',
    popupRateTitle: 'Your opinion matter to us!',
    popupRateMsg: 'We work super hard to make ' + DeviceInfo.getApplicationName() + ' better for you, and would love to know: how would you rate our app?',
    popupRateMsgBtn1Text: 'Submit',
    popupRateMsgBtn2Text: 'No Thanks',
    kycBenefits: 'Single KYC Form Benefits',
    requestoffernow: 'Request for the offer now.',
    requestFreeAccess: 'Request Free Access',
    mySchoolCondtion: '*Apply in any 4 schools for free of cost \n *Terms and Conditions applied.',
    selectRelationShipSelect: 'Your Relationship with student.',
    studentInfomation: `${'Student'}' Infomations`,
    thankIntMsg: 'Thanks for showing your interest in admission.',
    thankIntMsg1: 'Your request has been successfully submitted. Our dedicated support team will reach you within 24 hours.',
    thankIntBtnText: 'Submit Enquiry',
    dateofBirth: 'Date of Birth',
    gender: 'Gender',
    bloodGroup: 'Blood Group',
    birthMark: 'Birth Mark',
    heighcm: 'Height (cm)',
    emailAddress: 'Email Address',
    admissionIn: 'Admission In',
    previousStd: 'Previous Std.',
    currentSchool: 'Current School',
    fatherName: `${'Father'}'s Name`,
    motherName: `${'Mother'}'s Name`,
    fatherMobileNo: 'Mobile No. (Father)',
    motherMobileNo: 'Mobile No. (Mother)',
    annualIncome: 'Annual Income',
    address1: 'Address Line 1',
    address2: 'Address Line 2',
    pincode: 'Pincode',
    chancesadmission: 'Fill this form to maximize your chances of admission.',
    Requested: 'Requested',
    ScheduleTest: 'Schedule Test',
    ScheduleAdmissionTest: 'Schedule your Admission Test',
    Proceed: 'Proceed',
    SelectDate: 'Select Date',
    SelectTime: 'Select Time',
    ScheduleEntranceTest: 'Schedule Entrance Test',
    TimeLeft: 'Time Left',
    TimeLeftTitle: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit,sed diam nonummy nibh euismod tincidunt ut laoreet dolo',
    AttemptTest: 'Attempt Test',
    PreviewTest: 'Preview Test',
    EntranceFees: 'Entrance Fees',
    Checkout: 'Checkout',
    OrderSummary: 'Order Summary',
    ChoosePaymentMethods: 'Choose a Payment Methods',
    Notifications: 'Notifications'

}
export default BaseText;